config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  resources :documentation, only: :index

  get 'sitemap.xml' => 'home#sitemap', format: :xml, as: :sitemap
  get 'robots.:format' => 'home#robots', format: :text, as: :robots

  resources :formulas, only: [:index, :show], path: '' do
    member do
      post :refresh
      get :refresh_description # Redirect with 301 to the formula show page
    end

    collection do
      get :search
    end

    resources :dependents, only: [:index]
    resources :dependencies, only: [:index]
  end

  namespace :formulas do
    resources :news, only: :index
    resources :trendings, only: :index
  end

  root to: 'formulas#index'
end

app/models/homebrew/formula.rb
#
# Homebrew namespace
#
# This module embed any codes related to Homebrew for Mac
#
# @author [guillaumeh]
#
module Homebrew
  # A Homebrew formula
  #
  # @author [guillaumeh]
  #
  class Formula < ApplicationRecord
    # @nodoc ~~~ virtual attributes ~~~
    cattr_accessor :detected_service

    # @nodoc ~~~ special behaviours ~~~
    acts_as_punchable
    serialize :yearly_hits, Array

    # @nodoc ~~~ callbacks ~~~
    before_validation :initialize_yearly_hits_if_needed
    before_create :touch
    after_update :fetch_description

    # @nodoc ~~~ links ~~~
    # ~ Dependencies ~
    has_many :formula_dependencies, dependent: :destroy
    has_many :dependencies, through: :formula_dependencies
    has_many :formula_dependents,
             class_name: 'Homebrew::FormulaDependency',
             foreign_key: :dependency_id
    has_many :dependents, through: :formula_dependents, source: :formula
    # ~ Conflicts ~
    has_many :formula_conflicts, dependent: :destroy
    has_many :conflicts, through: :formula_conflicts
    has_many :revert_formula_conflicts,
             class_name: 'Homebrew::FormulaConflict',
             foreign_key: :conflict_id
    has_many :revert_conflicts,
             through: :revert_formula_conflicts,
             source: :formula

    # @nodoc ~~~ validations ~~~
    validates :filename, presence: true, uniqueness: true
    validates :name, presence: true

    # @nodoc ~~~ scopes ~~~
    scope :externals, -> { where(external: true) }
    scope :internals, -> { where(external: false) }
    scope :active, -> { where(touched_on: Import.last_succes_date_or_today) }
    scope :new_this_week, lambda {
      where("created_at BETWEEN LOCALTIMESTAMP - INTERVAL '7 days' " \
            'AND LOCALTIMESTAMP')
    }
    scope :inactive, lambda {
      where('touched_on < ?', Import.last_succes_date_or_today)
    }
    scope :with_a_description, -> { where('description is not NULL') }

    # @nodoc ~~~ custom class methods ~~~

    # @nodoc ~~~ custom instance methods ~~~

    #
    # Set the touched_on field
    #
    # The touched_on field is used in order to detect
    # deleted formula. When this field is older than
    # the day of today, it means the formula wasn't
    # touched when the background worker ran, so the
    # formula wasn't present from the Homebrew git repo.
    #
    def touch
      self.touched_on = Time.now.utc.to_date
    end

    def inactive?
      return false unless Import.last_succes_date_or_today

      touched_on < Import.last_succes_date_or_today
    end

    #
    # Determine if the formula has a description
    #
    # @return [Boolean] true if the formula has a description in DB
    #   otherwise false
    def description?
      self[:description].present?
    end

    #
    # Names of the formulas which are dependent
    # on the current formula.
    #
    # @return [Array] with the names of the fromulas
    def dependent_names
      dependents.map(&:name)
    end

    def detect_service
      service_detection = ServiceDetection.new(homepage)
      service_detection.detected_service
    end

    def update_description_from!(html)
      # Update the detected_service
      self.detected_service = detect_service

      # Initialize a new Homebrew::Formula::Description
      # which will be responsible to extract the formula
      # description from the readed homepage content.
      description = Homebrew::Formula::Description.new(self)
      description.lookup_from(html)

      return unless description.found?
      return if update_attributes(
        description: description.text,
        description_automatic: true
      )

      Rails.logger.warn 'Unable to update description with text ' \
                        "#{description.text}"
    end

    def reference
      "Extracted automatically from #{name} homepage" if description_automatic?
    end

    #
    # Get if the formula is new
    #
    # @return [Boolean] return true if new otherwise false
    def new?
      created_at.to_date == Time.now.utc.to_date
    end

    def as_json(_options = {}) # rubocop:disable Metrics/AbcSize
      {
        formula: name.downcase,
        description: description.to_s,
        reference: reference.to_s,
        homepage: homepage.to_s,
        version: version.to_s,
        new: new?,
        dependencies: dependencies.map(&:name).sort,
        dependents: formula_dependents.map(&:formula).map(&:name).sort
      }
    end # rubocop:enable Metrics/AbcSize

    def tags
      []
    end

    #
    # Build the Homebrew's github URL to the current formula file
    #
    def url
      formula_url = Rails.configuration.homebrew.git_repository.url
      formula_url = formula_url.gsub(/\.git$/, '/tree/master/Formula/')
      formula_url << filename
      formula_url << '.rb'
    end

    #
    # Build an array of numbers representing the amount of hits per months per
    # months for a year time window. Used in order to build the formula visits
    # graph.
    #
    def year_hits
      yearly_hits
    end

    #
    # Returns the highest amount of hits in the last year.
    #
    def heighest_hit
      year_hits.max
    end

    private

    def year_and_months
      12.times.map do |month_num|
        I18n.l(Date.today - month_num.month, format: '%Y%m')
      end
    end

    def fetch_description
      # Don't update the description
      # until the homepage is updated
      return unless saved_change_to_attribute?(:homepage)

      FormulaDescriptionFetchWorker.perform_async(id)
    end

    def month_hits_for(year_and_months)
      months_hits = Punch.unscoped
                         .group('year_and_month')
                         .where(punchable: self,
                                year_and_month: Array(year_and_months))
                         .count
      Array(year_and_months).each do |year_and_month|
        next if months_hits.key?(year_and_month)
        months_hits[year_and_month] = 0
      end

      months_hits.values.reverse
    end

    def initialize_yearly_hits_if_needed
      return if yearly_hits.is_a?(Array) && yearly_hits.present?

      if yearly_hits.is_a?(String)
        self.yearly_hits = JSON.parse(yearly_hits)
        return true
      end

      self.yearly_hits = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    end

    def update_yearly_hits!
      update(yearly_hits: month_hits_for(year_and_months))
    end
  end
end

app/models/homebrew/formula/description.rb
module Homebrew
  class Formula
    #
    # Extract the Homebrew::Formula description from its homepage
    #
    # @author [guillaumeh]
    #
    class Description
      attr_reader :text

      #
      # Instanciate a new Homebrew::Formula::Description
      # @param  formula [Homebrew::Formula] Formula for which the description
      #   has to be extracted
      #
      # @return [Homebrew::Formula::Description] Returns a new instance of
      #   Homebrew::Formula::Description
      def initialize(formula)
        @formula = formula
        @text = nil
      end

      #
      # Look up for a description in the given string
      # @param  content [String] String containing somewhere the description
      #
      def lookup_from(content)
        @html = Nokogiri::HTML(content)
        grab_description
      end

      #
      # Determine if a description has been found
      #
      # @return [Boolean] true if a description has been found otherwise false
      def found?
        @text.present?
      end

      private

      def software_description_strategy
        case @formula.detected_service
        when :github
          SoftwareDescriptionFetchers::Strategies::Github.new(@html)
        when :google_code
          SoftwareDescriptionFetchers::Strategies::GoogleCode.new(@html)
        else
          SoftwareDescriptionFetchers::Strategies::Default.new(
            @html, name: clean_name(@formula.name),
                   filename: clean_name(@formula.filename)
          )
        end
      end

      def grab_description
        @text = software_description_strategy.fetch
      end

      def clean_name(name)
        return name.split('@').first if name.include?('@')

        name
      end
    end
  end
end

app/controllers/formulas/news_controller.rb
module Formulas
  class NewsController < ApplicationController
    before_action :new_formulae_since_a_week, only: :index

    def index
    end

    private

    def new_formulae_since_a_week
      @new_formulae_since_a_week = Homebrew::Formula.internals
                                                    .new_this_week
                                                    .order(:name)
    end
  end
end

app/controllers/formulas/trendings_controller.rb
module Formulas
  class TrendingsController < ApplicationController
    before_action :trending_formulae, only: :index

    def index
    end

    private

    def trending_formulae
      @trending_formulae = Homebrew::Formula.most_hit(1.month.ago, nil)
                                            .page(params[:page])
    end
  end
end

app/controllers/formulas_controller.rb
class FormulasController < ApplicationController
  before_action :current_object, only: [:show, :refresh, :refresh_description]

  caches_action :index, cache_path: 'formulas'
  cache_sweeper :formulas_sweeper

  def index
    respond_to do |format|
      format.html do
        @trending_formulae = Homebrew::Formula.most_hit(1.month.ago, 8)
        @inactive_formulas = Homebrew::Formula.internals
                                              .inactive
                                              .order(:name)
                                              .limit(8)
        @new_formulae_since_a_week = Homebrew::Formula.internals
                                                      .new_this_week
                                                      .order(:name)
                                                      .limit(8)
      end
      format.json do
        render json: Homebrew::Formula.internals.active.order(:name)
      end
    end
  end

  def show
    unless @formula.inactive?
      @formula.punch(request)
      @formula.send(:update_yearly_hits!)
    end

    respond_to do |format|
      format.html
      format.json { render json: @formula, status: :ok }
    end
  end

  def refresh
    FormulaDescriptionFetchWorker.perform_async(@formula.id)
    flash[:success] = t('messages.request_successfully_submitted')

    respond_to do |format|
      format.html do
        @formula.reload

        render action: :show
      end
      format.js
    end
  end

  def refresh_description
    redirect_to formula_url(@formula.name), status: :moved_permanently
  end

  def search_term
    @search_term ||= params.require(:search).permit(:terms, :names, :filenames,
                                                    :descriptions, :term)
    @search_term.merge(page: params[:page]) if @search_term
  rescue ActionController::ParameterMissing
    nil
  end

  def search
    @search_context = SearchFormulas.call(search_term)
    updates_params_from_search_context! if @search_context.success?

    render action: :index
  end

  private

  def current_object
    @formula = Homebrew::Formula.find_by!('LOWER(name) = ?',
                                          params[:id].downcase)
  rescue ActiveRecord::RecordNotFound
    respond_to do |format|
      format.html do
        flash[:error] = 'This formula doesn\'t exists'
        redirect_to root_url
      end
      format.json { render json: {}, status: :not_found }
    end
  end

  def updates_params_from_search_context!
    params[:search][:terms] = @search_context.terms
    @search_term[:terms] = @search_context.terms
    params[:search][:names] = @search_context.names
    params[:search][:filenames] = @search_context.filenames
    params[:search][:descriptions] = @search_context.descriptions
  end
end

app/views/formulas/_formula.html.slim
.col-xs-12.col-sm-6.col-lg-3
  .card.mb-4
    .card-body
      h5.card-title
        = link_to formula.name.truncate(20), formula_path(formula.name)
      p.card-text== formula.description.try(:truncate, 110, omission: ('... ' + link_to(t('read_more'), formula_path(formula.name)))) || t('not_available')
      span.sparkline id="#{formula.id}" data-sparkline="#{formula.year_hits}" data-top-sparkline="#{formula.heighest_hit}"
    .card-footer
      small.text-muted.align-middle.float-right
        = t('distance_of_time_since_updated_ago', dotiw: distance_of_time_in_words(Date.today, formula.created_at))
      - if formula.tags.present?
        ul.tag-cloud
          - formula.tags.each do |formula_tag|
            li
              = link_to formula_tag.name, '#', class: 'tag'

app/views/formulas/index.html.slim
- meta title: Rails.configuration.title

section.jumbotron.text-center
  .container
    h1.jumbotron-heading= t('.jumbotron.title')
    p.lead.text-muted= t('.jumbotron.text')
    br
    p
      = form_for :search, url: search_formulas_path, method: :get do |f|
        .input-group
          = f.search_field :terms, class: 'form-control', placeholder: t('search'), value: @search_term && @search_term[:terms]

          .input-group-btn
            = button_tag type: :submit, class: 'btn btn-search', id: 'formula_search' do
              = octicon('search')
        .form-check.form-check-inline.mt-4
          = f.label :names, class: 'form-check-label' do
            = f.check_box :names, class: 'form-check-input', checked: params[:search].present? ? params[:search][:names] == '1' : true
            = t('names')
        .form-check.form-check-inline.mt-4
          = f.label :filenames, class: 'form-check-label' do
            = f.check_box :filenames, class: 'form-check-input', checked: params[:search].present? ? params[:search][:filenames] == '1' : true
            = t('filenames')
        .form-check.form-check-inline.mt-4
          = f.label :descriptions, class: 'form-check-label' do
            = f.check_box :descriptions, class: 'form-check-input', checked: params[:search].present? ? params[:search][:descriptions] == '1' : true
            = t('descriptions')

    br
    p
      iframe src="http://ghbtns.com/github-btn.html?user=zedtux&repo=brewformulas.org&type=watch&count=true&size=large" allowtransparency="true" frameborder="0" scrolling="0" width="170" height="30"
      iframe src="//www.tipeee.com/brewformulas-org/embed/button"  allowtransparency="true" frameborder="0" scrolling="0" width="170" height="30"

    p.lead
      ' You can support us on
      = link_to "Tipeee.com", 'https://www.tipeee.com/brewformulas-org', target: '_blank'
      '  now by clicking the "Tip!" button

.formulae-back
  - if @trending_formulae && @trending_formulae.size.keys.try(:size) > 0
    .container.mb-5
      .row
        .col-12
          h2.float-left= t('trending').pluralize.capitalize
          = link_to t('see_more'), formulas_trendings_path, class: 'btn btn-outline-primary float-right'
      .row
        .col-12
          hr
      .row#trendings
        = render partial: 'formula', collection: @trending_formulae

  - if @new_formulae_since_a_week.present?
    .container.mb-5
      .row
        .col-12
          h2.float-left= t('.news')
          = link_to t('see_more'), formulas_news_index_path, class: 'btn btn-outline-primary float-right'
      .row
        .col-12
          hr
      .row#news
        = render partial: 'formula', collection: @new_formulae_since_a_week

  - if @inactive_formulas.present?
    .container.mb-5
      .row
        .col-12
          h2.float-left= t('.inactives')
          = link_to t('see_more'), '#', class: 'btn btn-outline-primary float-right'
      .row
        .col-12
          hr
      .row#inactives
        = render partial: 'formula', collection: @inactive_formulas

  - if action_name == 'search'
    - if @search_context.failure?
      p.h4.text-center= t('messages.search_error')
      '
      .text-center.text-danger
        = @search_context.errors.full_messages
    - else
      - if @search_context.result_count.zero?
        p.h4.text-center== t('messages.sorry_nothing_found', terms: @search_term[:terms])
      - else
        .container.mb-5
          .row
            .col-12
              h2.float-left
                = t('.results')
                '
                span class="badge badge-default badge-pill" title="#{t('.search_result_count')}"= @search_context.result_count
          .row
            .col-12
              hr
          .row#pagination
            = render partial: 'formula', collection: @search_context.results

            p.pagination
              = link_to_next_page @search_context.results, t('next_page'), remote: true

app/views/formulas/index.js.erb
// Append new data
$("<%= j render(partial: 'formulas/formula', collection: @search_context.results) %>").appendTo($(".row#pagination"));

// Update pagination link
<% if @search_context.results %>
  <% if @search_context.results.last_page? %>
    $('.pagination').html('');
  <% else %>
    $('.pagination').html("<%= j link_to_next_page(@search_context.results, I18n.t('next_page'), remote: true) %>");
  <% end %>
<% end %>

app/views/formulas/refresh.js.erb
UnobtrusiveFlash.showFlashFromCookies();

app/views/formulas/show.html.slim
- meta title: @formula.name, description: truncate(@formula.description.presence || Rails.configuration.description, length: 160)

.container.mt-5
  .row.mt-2
    .col
      h1
        = @formula.name
        - unless @formula.external?
          small.ml-3= @formula.filename
        '
        span.badge class="badge-#{@formula.inactive? ? 'danger' : 'success'}"= @formula.inactive? ? t('inactive') : t('active')
        - unless @formula.external?
          .float-right
            = link_to 'Tweet', 'https://twitter.com/share', class: 'twitter-share-button', data: { text: "I have installed #{@formula.name} with homebrew", via: 'brewformulas', related: 'machomebrew', size: 'large' }

      - if @formula.external?
        p.text-info= t('.external_formula_description')

      hr

  .row.mt-2
    .col-lg-8
      h2= t('description').capitalize
      - if @formula.description?
        blockquote.blockquote
          p.mb-0= @formula.description
          - if @formula.description_automatic?
            footer.blockquote-footer
              == t('.extracted_automatically_from', title: @formula.homepage, name: @formula.name)
      - else
        .alert.alert-info
          = t('.no_description_available')
          '
          == t('.you_can_request_update_with_link', link: refresh_formula_path(@formula.name))
      = link_to t('.open_new_issue'), homebrew_new_issue_github_url(title: @formula.name), class: 'btn btn-secondary mb-3', data: { toggle: 'tooltip' }, title: t('.report_issue_title'), target: '_blank'
    .col-lg-4
      dl.dl-horizontal
        dt= t('homepage').capitalize
        dd
          a href="#{@formula.homepage}" target="_blank"= @formula.homepage
        dt= t('version').capitalize
        dd= @formula.version || t('unavailable').capitalize
        - unless @formula.inactive?
          dt= t('source_file').capitalize
          dd
            = octicon 'mark-github'
            '
            = link_to t('source_file'), @formula.url, target: '_blank'
        dt= t('hits')
        dd= @formula.hits

  - unless @formula.external?
    .row.mt-3
      .col
        h4= t('.install_formula', name: @formula.name)
        pre
          code= "brew install #{@formula.filename}"
        br

  .row.mt-2
    .col
      h4
        = t('dependency').pluralize.capitalize
        '
        span class="badge badge-default badge-pill" title="#{t('.dependency_count')}"= @formula.dependencies.size
      - if @formula.dependencies.blank?
        p= t('.no_dependencies')
      - else
        p= t('.the_following_dependencies_will_be_installed', dependency: pluralize(@formula.dependencies.size, t('dependency'), nil, no_count_if_one: true), name: @formula.name)
        span#formula-dependencies
          = render partial: 'shared/formula_list', locals: { formulas: @formula.dependencies.order(:name).first(3), formula_count: @formula.dependencies.count, formula_name: @formula.name, show_other_formulae_link: true, formula_type: 'dependencies' }

  - if @formula.dependents.present?
    .row.mt-2
      .col
        h4
          = t('dependent').capitalize.pluralize
          '
          span class="badge badge-default badge-pill" title="Dependents count"= @formula.dependents.size
        p.dependents
          = t('formulas.show.this_formula_is_required_by')
          '
          span#formula-dependents
            = render partial: 'shared/formula_list', locals: { formulas: @formula.dependents.order(:name).first(3), formula_count: @formula.dependents.count, formula_name: @formula.name, show_other_formulae_link: true, formula_type: 'dependents' }

  - if @formula.conflicts.present?
    .row.mt-2
      .col
        h4
          = t('conflict').capitalize.pluralize
          '
          span class="badge badge-default badge-pill" title="#{t('.conflict_count')}"= @formula.conflicts.size
        p.conflicts
          = t('.this_formula_is_in_conflict_with_the_following')
          '
          ul.list-inline#formula_conflicts
            - @formula.conflicts.each do |conflict|
              li.conflict
                = link_to formula_path(conflict.name) do
                  = octicon 'link'
                  '
                  = conflict.name