config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  resources :documentation, only: :index

  get 'sitemap.xml' => 'home#sitemap', format: :xml, as: :sitemap
  get 'robots.:format' => 'home#robots', format: :text, as: :robots

  resources :formulas, only: [:index, :show], path: '' do
    member do
      post :refresh
      get :refresh_description # Redirect with 301 to the formula show page
    end

    collection do
      get :search
    end

    resources :dependents, only: [:index]
    resources :dependencies, only: [:index]
  end

  namespace :formulas do
    resources :news, only: :index
    resources :trendings, only: :index
  end

  root to: 'formulas#index'
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = metamagic site: 'BrewFormulas', title: [:title, :site], separator: ' — ', description: Rails.configuration.description, author: Rails.configuration.author, keywords: Rails.configuration.keywords
    = csrf_meta_tags
    = action_cable_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = favicon_link_tag 'favicon.ico', rel: 'shortcut icon'
    = javascript_include_tag 'application'

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"

    - if Rails.env.production?
      javascript:
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
        ga('create', 'UA-45980206-1', 'brewformulas.org');
        
        !function(a,b){var c=window;c.SessionStack=a,c[a]=c[a]||function(){
        c[a].q=c[a].q||[],c[a].q.push(arguments)},c[a].t=b;var d=document.createElement("script");
        d.async=1,d.src="https://cdn.sessionstack.com/sessionstack.js";
        var e=document.getElementsByTagName("script")[0];e.parentNode.insertBefore(d,e);
        }("sessionstack","5015a659141541fca546e8063b3eb11e");

  body class="#{controller_name} #{action_name}"
    #navbarHeader.bg-dark.collapse aria-expanded="false"
      .container
        .row
          .col-sm-8.py-4
            h4.text-white= t('about').capitalize
            p.text-muted= t('.about_text')
          .col-sm-4.py-4
            h4.text-white= t('some_links').capitalize
            ul.list-unstyled
              li
                = link_to t('links.twitter'), 'https://twitter.com/brewformulas', class: 'text-white', target: '_blank'
              li.hidden-lg-up
                = link_to 'Homebrew project', 'https://brew.sh', class: 'text-white', target: '_blank'
              li
                = link_to t('.api_documentation'), documentation_index_path, class: 'text-white'

    .navbar.navbar-toggleable-md.navbar-light
      .container.d-flex.justify-content-between
        = link_to 'Homebrew Formulas', root_url, class: 'navbar-brand'

        ul.navbar-nav.mr-auto.mt-2.mt-md-0.hidden-md-down
          li.nav-item.active
            = link_to 'Homebrew project', 'https://brew.sh', class: 'nav-link', target: '_blank'

        button.navbar-toggler.d-block.collapsed type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation"
          span.navbar-toggler-icon

    // Flash messages
    - if Rails.env.test?
      = flash_messages
    - else
      .unobtrusive-flash-container

    = yield

    footer.text-muted.mt-3
      .container
        p.float-right
          = link_to 'Back to top', '#'

        p= t('credit_line')